package Interfaz;

import aplicacion.ModeloTablaEjemplares;
import aplicacion.Ejemplar;
import aplicacion.Equipamiento;
import aplicacion.Establecimiento;
import javax.swing.JTable;

/**
 *
 * @author alumnogreibd
 */
public class VEjemplar extends javax.swing.JDialog {

    aplicacion.FachadaAplicacion fa;
    private ModeloTablaEjemplares mte;
    private VBEquipamiento padre;
    private Integer establecimiento;
    private Integer id_equipamiento;
    private Equipamiento equipamiento;
    private Integer id_ejemplar;

    /**
     * Creates new form VEjemplar
     */
    public VEjemplar(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa) {
        super(parent, modal);
        this.fa = fa;
        initComponents();

        this.mte = new ModeloTablaEjemplares();
        tablaEjemplares.setModel(mte);
        if (mte.getRowCount() > 0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
        }

        this.establecimiento = getEstablecimientoActual().getId_establecimiento();

        btnGuardar.setEnabled(false);
        btnBorrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoIDEquip = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoIDEjemplar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEjemplares = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoAnoCompra = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numEjemplares = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de ejemplares");

        jLabel1.setText("Equipamiento:");

        jLabel2.setText("ID ejemplar:");

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaEjemplares.setModel(new ModeloTablaEjemplares());
        tablaEjemplares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEjemplaresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEjemplares);

        jLabel3.setText("GESTIONAR DATOS DEL EJEMPLAR");

        jLabel4.setText("Descripción:");

        jLabel5.setText("Año de compra:");

        campoDescripcion.setColumns(20);
        campoDescripcion.setRows(5);
        campoDescripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(campoDescripcion);

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(255, 255, 255));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnBorrar.setText("Eliminar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setText("AÑADIR EJEMPLARES AL EQUIPAMIENTO");

        jLabel7.setText("Ejemplares a añadir:");

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoIDEjemplar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(campoIDEquip)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoAnoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnGuardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)
                        .addComponent(jLabel6))
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoIDEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoIDEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(campoAnoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnBorrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addComponent(btnAdd))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEjemplares();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaEjemplaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEjemplaresMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());

        Integer id_ejemplar = mte.obtenerEjemplar(tablaEjemplares.getSelectedRow()).getId_ejemplar();

        Ejemplar e = fa.visualizarEjemplar(id_ejemplar, equipamiento, establecimiento);

        campoDescripcion.setText(e.getDescripcion());
        campoAnoCompra.setText(e.getAno_compra().toString());
        campoIDEjemplar.setText(e.getId_ejemplar().toString());
        campoAnoCompra.setEditable(false);

        btnGuardar.setEnabled(true);
        btnBorrar.setEnabled(true);
    }//GEN-LAST:event_tablaEjemplaresMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Ejemplar e;
        e = new Ejemplar(equipamiento, Integer.parseInt(campoIDEjemplar.getText()), campoDescripcion.getText(), Integer.parseInt(campoAnoCompra.getText()), establecimiento);
        fa.modificarEjemplar(e);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        fa.borrarEjemplar(Integer.parseInt(campoIDEjemplar.getText()), equipamiento, establecimiento);
        campoIDEjemplar.setText(null);
        this.actualizarTabla();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (!this.numEjemplares.getText().isEmpty()) {
            int cuantos = Integer.parseInt(numEjemplares.getText());

            Ejemplar ej = new Ejemplar(equipamiento, campoDescripcion.getText(), establecimiento);
            for (int i = 0; i < cuantos; i++) {
                fa.insertarEjemplar(equipamiento.getId(), ej);
            }
            this.actualizarTabla();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField campoAnoCompra;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JTextField campoIDEjemplar;
    private javax.swing.JTextField campoIDEquip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numEjemplares;
    private javax.swing.JTable tablaEjemplares;
    // End of variables declaration//GEN-END:variables

    public void buscarEjemplares() {
        ModeloTablaEjemplares mte;

        mte = (ModeloTablaEjemplares) tablaEjemplares.getModel();

        try {
            if (!campoIDEquip.getText().isEmpty()) {
                this.equipamiento = fa.consultarEquipamiento(Integer.parseInt(campoIDEquip.getText()));
                if (!campoIDEjemplar.getText().isEmpty()) {
                    mte.setFilas(fa.obtenerEjemplares(Integer.parseInt(campoIDEjemplar.getText()), establecimiento, equipamiento));
                } else {
                    mte.setFilas(fa.obtenerEjemplares(establecimiento, equipamiento));
                }
                if(fa.obtenerEjemplares(establecimiento, equipamiento).isEmpty()){
                    fa.muestraExcepcion("No existen ejemplares. Añádelos en la parte inferior de la ventana.");
                }
            } else fa.muestraExcepcion("Es necesario introducir al menos el ID del equipamiento.");
        } catch (Exception e) {
            this.fa.muestraExcepcion("Ooops, algo ha salido mal en la búsqueda.");
        }

        if (mte.getRowCount() > 0) {
            tablaEjemplares.setRowSelectionInterval(0, 0);
        }
    }

    private Establecimiento getEstablecimientoActual() {
        return fa.getEstablecimientoActual();
    }

    public void actualizarTabla() {

        this.buscarEjemplares();
        this.mte = (ModeloTablaEjemplares) tablaEjemplares.getModel();

        id_ejemplar = this.mte.obtenerEjemplar(tablaEjemplares.getSelectedRow()).getId_ejemplar();

        Ejemplar e = fa.visualizarEjemplar(id_ejemplar, equipamiento, establecimiento);

        campoAnoCompra.setText(e.getAno_compra().toString());
        campoDescripcion.setText(e.getDescripcion());

        this.tablaEjemplares.updateUI();
    }

}
