package Interfaz;

import aplicacion.Actividad;
import aplicacion.ModeloTablaUsuarios;
import aplicacion.Sesion;
import aplicacion.Usuario;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author alumnogreibd
 */
public class VGestionarUsersSesiones extends javax.swing.JDialog {
    
    private aplicacion.FachadaAplicacion fa;
    private VSesiones padre;
    private Sesion sesion;
    private ModeloTablaUsuarios mtu1;
    private ModeloTablaUsuarios mtu3;
    private Usuario usuario;
    private Integer establecimiento;
    private Actividad actividad;

    /**
     * Creates new form VGestionarSesiones
     */
    public VGestionarUsersSesiones(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Sesion s, Actividad a) {
        super(parent, modal);
        initComponents();
        this.fa = fa;
        this.sesion = s;
        this.actividad = a;
        this.establecimiento = fa.getEstablecimientoActual().getId_establecimiento();
        
        this.mtu1 = new ModeloTablaUsuarios();
        tablaUsuarios1.setModel(mtu1);
        if (mtu1.getRowCount() > 0) {
            tablaUsuarios1.setRowSelectionInterval(0, 0);
        }
        
        this.mtu3 = new ModeloTablaUsuarios();
        tablaUsuarios3.setModel(mtu3);
        if (mtu3.getRowCount() > 0) {
            tablaUsuarios3.setRowSelectionInterval(0, 0);
        }
        
        btnAdd1.setEnabled(false);
        btnAdd2.setEnabled(false);
        btnEliminar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoDNI1 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios3 = new javax.swing.JTable();
        btnAdd1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        checkBoxSocioa = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textoDNI2 = new javax.swing.JTextField();
        btnAdd2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textoDNI3 = new javax.swing.JTextField();
        btnBuscar2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios1 = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar sus usuarios/as");

        jLabel1.setText("AÑADIR USUARIO/A EXISTENTE");

        jLabel2.setText("DNI");

        btnBuscar1.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        tablaUsuarios3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaUsuarios3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarios3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios3);

        btnAdd1.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd1.setText("Añadir");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("CREAR Y AÑADIR USUARIO/A");

        jLabel5.setText("Nombre:");

        checkBoxSocioa.setText("Socio/a");

        jLabel6.setText("E-mail:");

        jLabel7.setText("Teléfono:");

        jLabel4.setText("DNI:");

        textoDNI2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDNI2KeyPressed(evt);
            }
        });

        btnAdd2.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd2.setText("Añadir");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("ELIMINAR USUARIOS/AS");

        jLabel9.setText("DNI");

        btnBuscar2.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnBuscar2.setText("Buscar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });

        tablaUsuarios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaUsuarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuarios1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaUsuarios1);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAdd1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(btnBuscar1))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textoEmail)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(26, 26, 26)
                                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(44, 44, 44)
                            .addComponent(checkBoxSocioa)))
                    .addComponent(btnAdd2))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnBuscar2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoDNI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnAdd1)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textoDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkBoxSocioa))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(179, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd2)
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoDNI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(btnBuscar2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(20, 20, 20))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        buscarUsuariosDisponibles();
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void tablaUsuarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarios1MouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String dni_user = source.getModel().getValueAt(row, 0) + "";
        
        this.usuario = fa.visualizarUsuario(dni_user);
        
        btnAdd1.setEnabled(true);
    }//GEN-LAST:event_tablaUsuarios1MouseClicked

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        if (fa.visualizarUsuario(usuario.getDni_usuario()) != null) {
            if (!this.hayPlazas()) {
                fa.muestraExcepcion("No hay plazas en esta sesion.");
            } else {
                fa.addUserToSesion(this.usuario, this.sesion.getIdSesion(), this.establecimiento);
                this.actualizarTabla1();
            }
        } else {
            fa.muestraExcepcion("El usuario (ya) no pertenece a nuestros gimnasios. Por favor, lo tiene que dar de alta en la columna de su derecha.");
        }

    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        if (this.checkFields()) {
            if (fa.visualizarUsuario(textoDNI2.getText()) == null) {
                this.usuario = new Usuario(textoDNI2.getText(), textoNombre.getText(), textoEmail.getText(), textoTelefono.getText(), checkBoxSocioa.isSelected());
                fa.insertarUsuario(usuario);
                if (!this.hayPlazas()) {
                    fa.muestraExcepcion("No hay plazas en esta sesión.");
                } else {
                    fa.addUserToSesion(this.usuario, this.sesion.getIdSesion(), this.establecimiento);
                    this.actualizarTabla1();
                }
            } else {
                fa.muestraExcepcion("Este usuario ya pertenece a nuestros gimnasios. Por favor, búsquelo en la columna de su izquierda.");
            }
        } else {
            fa.muestraExcepcion("Es necesario cubrir todos los campos.");
        }
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        buscarUsuariosDeEsaSesion();
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        fa.eliminarUsuarioSesion(usuario, sesion.getIdSesion(), this.establecimiento);
        this.actualizarTabla3();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuarios3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuarios3MouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String dni_user = source.getModel().getValueAt(row, 0) + "";
        
        this.usuario = fa.visualizarUsuario(dni_user);
        
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tablaUsuarios3MouseClicked

    private void textoDNI2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDNI2KeyPressed
        btnAdd2.setEnabled(true);
    }//GEN-LAST:event_textoDNI2KeyPressed
    
    public void buscarUsuariosDisponibles() {
        
        this.mtu1 = (ModeloTablaUsuarios) tablaUsuarios1.getModel();
        try {
            if (!textoDNI1.getText().isEmpty()) {
                mtu1.setFilas(fa.consultarPosiblesUsuarios(Integer.parseInt(textoDNI1.getText(), sesion.getIdSesion())));
            } else {
                java.util.List<Usuario> u = fa.consultarPosiblesUsuarios(sesion.getIdSesion());
                mtu1.setFilas(u);
            }
            
        } catch (Exception e) {
            this.fa.muestraExcepcion("Ooops, algo ha salido mal en la búsqueda.");
        }
        if (mtu1.getRowCount() > 0) {
            tablaUsuarios1.setRowSelectionInterval(0, 0);
        }
        
    }
    
    public void buscarUsuariosDeEsaSesion() {
        
        this.mtu3 = (ModeloTablaUsuarios) tablaUsuarios3.getModel();
        java.util.List<Usuario> users;
        try {
            if (!textoDNI3.getText().isEmpty()) {
                users = fa.consultarUsuariosdeUnaSesion(textoDNI3.getText(), sesion.getIdSesion());
                if (!users.isEmpty()) {
                    mtu3.setFilas(users);
                } else {
                    fa.muestraExcepcion("Aun no hay usuarios/as en esta sesión.");
                }
            } else {
                users = fa.consultarUsuariosdeUnaSesion(sesion.getIdSesion());
                if (!users.isEmpty()) {
                    mtu3.setFilas(users);
                } else {
                    fa.muestraExcepcion("Aun no hay usuarios/as en esta sesión.");
                }
            }
            
        } catch (Exception e) {
            this.fa.muestraExcepcion("Ooops, algo ha salido mal en la búsqueda.");
        }
        if (mtu1.getRowCount() > 0) {
            tablaUsuarios3.setRowSelectionInterval(0, 0);
        }
        
    }
    
    public boolean checkFields() {
        if (!textoDNI2.getText().isEmpty() && !textoEmail.getText().isEmpty()
                && !textoNombre.getText().isEmpty() && !textoTelefono.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    //Actualizar la tabla de usuarios
    public void actualizarTabla1() {
        buscarUsuariosDisponibles();
        this.tablaUsuarios1.updateUI();
    }

    //Actualizar la tabla de usuarios
    public void actualizarTabla3() {
        buscarUsuariosDeEsaSesion();
        this.tablaUsuarios3.updateUI();
    }
    
    public boolean hayPlazas() {
        int numUsuarios = fa.consultarUsuariosdeUnaSesion(sesion.getIdSesion()).size();
        int numPlazas = sesion.getPlazas();
        if (numUsuarios == numPlazas) {
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JCheckBox checkBoxSocioa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaUsuarios1;
    private javax.swing.JTable tablaUsuarios3;
    private javax.swing.JTextField textoDNI1;
    private javax.swing.JTextField textoDNI2;
    private javax.swing.JTextField textoDNI3;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoTelefono;
    // End of variables declaration//GEN-END:variables
}
