/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import aplicacion.ModeloTablaSesiones;
import aplicacion.Sesion;
import aplicacion.Usuario;
import javax.swing.JTable;

/**
 *
 * @author alumnogreibd
 */
public class VUsuarioSesiones extends javax.swing.JDialog {

    /**
     * Creates new form VUsuarioSesiones
     */
    private VPrincipal padre;
    aplicacion.FachadaAplicacion fa;
    private ModeloTablaSesiones mts;
    private Integer establecimiento;
    private Usuario user;
    private Sesion sesion;
    private int idSesion;

    public VUsuarioSesiones(java.awt.Frame parent, boolean modal, aplicacion.FachadaAplicacion fa, Usuario u) {
        super(parent, modal);
        initComponents();

        this.fa = fa;
        this.user = u;
        this.establecimiento = fa.getEstablecimientoActual().getId_establecimiento();
        this.textoUser.setText(user.getDni_usuario());
        this.textoUser.setEditable(false);
        btnQuitar.setEnabled(false);

        this.mts = new ModeloTablaSesiones();
        tablaSesiones.setModel(mts);
        if (mts.getRowCount() > 0) {
            tablaSesiones.setRowSelectionInterval(0, 0);
        }

        buscarSesiones();
    }

    public void buscarSesiones() {
        this.mts = (ModeloTablaSesiones) tablaSesiones.getModel();
        //buscamos
        java.util.List<Sesion> sesiones = fa.obtenerSesionesUsuario(this.user, this.establecimiento);
        if (!sesiones.isEmpty()) {
            this.mts.setFilas(sesiones);
            if (mts.getRowCount() > 0) {
                tablaSesiones.setRowSelectionInterval(0, 0);
            }

            this.mts = (ModeloTablaSesiones) tablaSesiones.getModel();
            this.idSesion = this.mts.obtenerSesion(tablaSesiones.getSelectedRow()).getIdSesion();
        } else fa.muestraExcepcion("No tiene sesiones asignadas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoUser = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSesiones = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar sus sesiones");

        jLabel1.setText("Usuario/a");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(789, 403));
        jScrollPane1.setRequestFocusEnabled(false);

        tablaSesiones.setModel(new aplicacion.ModeloTablaSesiones());
        tablaSesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSesionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSesiones);

        btnQuitar.setBackground(new java.awt.Color(255, 255, 255));
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 489, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnQuitar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaSesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSesionesMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        this.idSesion = (Integer) source.getModel().getValueAt(row, 0);

        this.sesion = fa.obtenerSesion(idSesion);
        
        btnQuitar.setEnabled(true);
    }//GEN-LAST:event_tablaSesionesMouseClicked

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        fa.borrarSesion(this.sesion);
        this.actualizarTabla();
    }//GEN-LAST:event_btnQuitarActionPerformed

    //Actualizar la tabla de usuarios
    public void actualizarTabla() {
        buscarSesiones();        
        this.tablaSesiones.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSesiones;
    private javax.swing.JTextField textoUser;
    // End of variables declaration//GEN-END:variables
}
